# @package _group_
common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: true
  save_dir: checkpoints

task:
  _name: masked_lm
  data: /data/tangqirui/Para/fairseq/data-bin/zwtext
  sample_break_mode: complete
  tokens_per_sample: 511
  shorten_method: truncate
#  mask_whole_words: true
  do_ch_wwm: true

criterion: masked_lm

dataset:
  batch_size: 32
  ignore_unused_valid_subsets: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.00005]
  max_update: 2000000
  update_freq: [12]

model:
  _name: roberta
  max_positions: 511
  dropout: 0.1
  attention_dropout: 0.1
  huggingface_pretrained: /data/tangqirui/Para/fairseq/huggingface/chinese_roberta_wwm_ext/pytorch_model.bin


